title: Avto renovatsia
email: g_cirkova@mail.bg
description: template
destination: docs
# baseurl: "/Slavi"
baseurl: ""
url: ""
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
